// src/data/models.ts
// Hand-written row types for the raw-SQLite data layer.
//
// These replace the types previously generated by `@prisma/client`. They
// describe the SHAPE the data layer returns to the rest of the app after
// row-mapping (see src/db.ts): datetimes as `Date`, integer booleans as
// `boolean`, and JSONB text columns parsed into values.

import type { Cardinality, ProjectRoleValue } from './schema'

/** Permissive JSON value (mirrors the old Prisma `JsonValue`). */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | Array<JsonValue>

export interface User {
  id: string
  username: string
  email: string
  passwordHash: string
  failedLoginAttempts: number
  lockedUntil: Date | null
  createdAt: Date
  updatedAt: Date
}

export interface Session {
  id: string
  tokenHash: string
  userId: string
  expiresAt: Date
  createdAt: Date
}

export interface ProjectMember {
  id: string
  projectId: string
  userId: string
  role: ProjectRoleValue
  createdAt: Date
  updatedAt: Date
}

export interface Project {
  id: string
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  ownerId: string | null
}

export interface ProjectInvite {
  id: string
  projectId: string
  role: ProjectRoleValue
  tokenHash: string
  createdByUserId: string
  maxUses: number | null
  usedCount: number
  expiresAt: Date
  revokedAt: Date | null
  createdAt: Date
}

export interface WhiteboardShareLink {
  id: string
  whiteboardId: string
  tokenHash: string
  createdByUserId: string
  expiresAt: Date | null
  revokedAt: Date | null
  createdAt: Date
}

export interface Folder {
  id: string
  name: string
  projectId: string
  parentFolderId: string | null
  createdAt: Date
  updatedAt: Date
}

export interface Whiteboard {
  id: string
  name: string
  projectId: string
  folderId: string | null
  canvasState: JsonValue | null
  textSource: string | null
  createdAt: Date
  updatedAt: Date
}

export interface DiagramTable {
  id: string
  whiteboardId: string
  name: string
  description: string | null
  positionX: number | null
  positionY: number | null
  width: number | null
  height: number | null
  createdAt: Date
  updatedAt: Date
}

export interface Column {
  id: string
  tableId: string
  name: string
  dataType: string
  isPrimaryKey: boolean
  isForeignKey: boolean
  isUnique: boolean
  isNullable: boolean
  description: string | null
  order: number
  createdAt: Date
  updatedAt: Date
}

export interface Relationship {
  id: string
  whiteboardId: string
  sourceTableId: string
  targetTableId: string
  sourceColumnId: string
  targetColumnId: string
  cardinality: Cardinality
  label: string | null
  routingPoints: JsonValue | null
  createdAt: Date
  updatedAt: Date
}

export interface CollaborationSession {
  id: string
  whiteboardId: string
  userId: string
  socketId: string
  cursor: JsonValue | null
  lastActivityAt: Date
  createdAt: Date
}
