// src/data/models.ts
// Hand-written row types for the raw-SQLite data layer.
//
// These replace the types previously generated by `@prisma/client`. They
// describe the SHAPE the data layer returns to the rest of the app after
// row-mapping (see src/db.ts): datetimes as `Date`, integer booleans as
// `boolean`, and JSONB text columns parsed into values.

import type {
  CanvasElementKind,
  CanvasElementProps,
  CanvasElementStyle,
  Cardinality,
  ConnectorStyle,
  ProjectRoleValue,
  ShapeKind,
  ShapeProps,
  ShapeStyle,
} from './schema'

/** Permissive JSON value (mirrors the old Prisma `JsonValue`). */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | Array<JsonValue>

export interface User {
  id: string
  username: string
  email: string
  passwordHash: string
  failedLoginAttempts: number
  lockedUntil: Date | null
  createdAt: Date
  updatedAt: Date
}

export interface Session {
  id: string
  tokenHash: string
  userId: string
  expiresAt: Date
  createdAt: Date
}

export interface ProjectMember {
  id: string
  projectId: string
  userId: string
  role: ProjectRoleValue
  createdAt: Date
  updatedAt: Date
}

export interface Project {
  id: string
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  ownerId: string | null
}

export interface ProjectInvite {
  id: string
  projectId: string
  role: ProjectRoleValue
  tokenHash: string
  createdByUserId: string
  maxUses: number | null
  usedCount: number
  expiresAt: Date
  revokedAt: Date | null
  createdAt: Date
}

export interface WhiteboardShareLink {
  id: string
  whiteboardId: string
  tokenHash: string
  createdByUserId: string
  expiresAt: Date | null
  revokedAt: Date | null
  createdAt: Date
}

/**
 * Public read-only share link for a CANVAS board.
 *
 * Structurally identical to `WhiteboardShareLink` but a distinct type over a
 * distinct table: the two reference different board kinds, and a single type
 * with a nullable id pair would make "which board does this link point at?"
 * a runtime question at every call site instead of a compile-time one.
 */
export interface CanvasBoardShareLink {
  id: string
  canvasBoardId: string
  tokenHash: string
  createdByUserId: string
  expiresAt: Date | null
  revokedAt: Date | null
  createdAt: Date
}

/**
 * Full-state capture of a whiteboard's diagram (GH #107 version history), as
 * returned FRESH by `captureWhiteboardState` — nested `createdAt`/`updatedAt`
 * are real `Date` objects straight from the data layer, never round-tripped
 * through JSON. D1: stored as a single self-contained JSON blob so it is
 * immune to future live-schema drift — everything needed to restore lives in
 * this object, including original entity UUIDs (reused verbatim on restore,
 * D3).
 *
 * See `PersistedSnapshotPayload` for the shape this becomes once it has been
 * written to and reloaded from the DB — the two are NOT interchangeable.
 *
 * `shapes`/`connectors` are REQUIRED here (tech-spec.md §6/FR-035a) — this is
 * a fresh capture, and `captureWhiteboardState` has an explicit
 * `Promise<SnapshotPayload>` return annotation, so omitting either key at the
 * capture site fails to compile. Contrast with `PersistedSnapshotPayload`
 * below, where both are OPTIONAL because every snapshot captured before this
 * feature existed has neither key. Do not make these optional here — that
 * would silently defeat the compile-time guard.
 */
export interface SnapshotPayload {
  whiteboard: {
    name: string
    canvasState: JsonValue | null
    textSource: string | null
  }
  tables: Array<DiagramTable & { columns: Array<Column> }>
  relationships: Array<Relationship>
  areas: Array<Area>
  shapes: Array<Shape>
  connectors: Array<Connector>
}

/**
 * Replaces `createdAt`/`updatedAt` with `string` — mirrors exactly what
 * `JSON.stringify`/`JSON.parse` do to a `Date` field during the
 * `toDbJson`/`fromDbJson` round-trip (`JSON.stringify` serializes a `Date` to
 * an ISO string; `JSON.parse` never revives it back to a `Date`). Keeps the
 * Date-vs-string mismatch statically visible in the type system instead of
 * relying solely on a code comment — a future `Date`-typed field added to
 * DiagramTable/Column/Relationship/Area will fail to compile here until this
 * mapped type (or its usage) is updated, rather than silently reaching
 * `restoreWhiteboardFromSnapshot` as an un-coerced `Date`.
 */
type WithPersistedDates<T extends { createdAt: Date; updatedAt: Date }> = Omit<
  T,
  'createdAt' | 'updatedAt'
> & {
  createdAt: string
  updatedAt: string
}

/**
 * The as-stored-and-reloaded shape of a SnapshotPayload — what
 * `WhiteboardSnapshot.payload` actually is once `mapWhiteboardSnapshot` has
 * parsed it back out of the `payload` JSON column (see `fromDbJson`). Every
 * nested `createdAt`/`updatedAt` is a `string`, matching what
 * `coerceStoredDate` in `whiteboard-snapshot.ts` is defending against at
 * runtime.
 *
 * `shapes`/`connectors` are OPTIONAL here — FR-035a. Every snapshot captured
 * before this feature existed has neither key, and that payload is a frozen
 * blob that is never migrated. `restoreWhiteboardFromSnapshot`'s parameter is
 * `SnapshotPayload | PersistedSnapshotPayload`, so `payload.shapes` narrows to
 * `Array<...> | undefined` and TypeScript refuses to compile a bare
 * `for (const shape of payload.shapes)` — the `?? []` at the restore call
 * site is the only thing that type-checks, not defensive style. Do NOT make
 * these required "for symmetry" — that turns every historical version
 * permanently un-restorable.
 */
export interface PersistedSnapshotPayload {
  whiteboard: {
    name: string
    canvasState: JsonValue | null
    textSource: string | null
  }
  tables: Array<
    WithPersistedDates<DiagramTable> & {
      columns: Array<WithPersistedDates<Column>>
    }
  >
  relationships: Array<WithPersistedDates<Relationship>>
  areas: Array<WithPersistedDates<Area>>
  shapes?: Array<WithPersistedDates<Shape>>
  connectors?: Array<WithPersistedDates<Connector>>
}

/**
 * WhiteboardSnapshot row (GH #107) — an immutable, point-in-time capture of
 * a whiteboard's full diagram state. `isAuto` distinguishes user-initiated
 * saves from the automatic "before restore" safety snapshot (D2). `payload`
 * is always the DB-reloaded (persisted) shape — see `PersistedSnapshotPayload`.
 */
export interface WhiteboardSnapshot {
  id: string
  whiteboardId: string
  label: string | null
  payload: PersistedSnapshotPayload
  createdByUserId: string | null
  isAuto: boolean
  createdAt: Date
}

export interface Folder {
  id: string
  name: string
  projectId: string
  parentFolderId: string | null
  createdAt: Date
  updatedAt: Date
}

export interface Whiteboard {
  id: string
  name: string
  projectId: string
  folderId: string | null
  canvasState: JsonValue | null
  textSource: string | null
  createdAt: Date
  updatedAt: Date
}

export interface DiagramTable {
  id: string
  whiteboardId: string
  name: string
  description: string | null
  positionX: number | null
  positionY: number | null
  width: number | null
  height: number | null
  createdAt: Date
  updatedAt: Date
}

export interface Column {
  id: string
  tableId: string
  name: string
  dataType: string
  isPrimaryKey: boolean
  isForeignKey: boolean
  isUnique: boolean
  isNullable: boolean
  description: string | null
  order: number
  createdAt: Date
  updatedAt: Date
}

export interface Relationship {
  id: string
  whiteboardId: string
  sourceTableId: string
  targetTableId: string
  sourceColumnId: string
  targetColumnId: string
  cardinality: Cardinality
  label: string | null
  routingPoints: JsonValue | null
  createdAt: Date
  updatedAt: Date
}

export interface CollaborationSession {
  id: string
  whiteboardId: string
  userId: string
  socketId: string
  cursor: JsonValue | null
  lastActivityAt: Date
  createdAt: Date
}

/**
 * Subject area (GH #106) — a named, colored background region that groups
 * tables. Membership is explicit (`memberTableIds`); areas do NOT own table
 * positions. `color` stores a palette id (see src/lib/area-colors.ts).
 */
export interface Area {
  id: string
  whiteboardId: string
  name: string
  color: string
  positionX: number
  positionY: number
  width: number
  height: number
  memberTableIds: Array<string>
  createdAt: Date
  updatedAt: Date
}

/**
 * A polymorphic drawn shape (Phase 1: shapes-and-connectors). Five kinds
 * (rectangle, ellipse, diamond, line, text) share the same row shape:
 * generic geometry in real columns, kind-specific data in `props`, visual
 * styling in `style`. See tech-spec.md §3 for the full rationale.
 */
export interface Shape {
  id: string
  whiteboardId: string
  kind: ShapeKind
  positionX: number
  positionY: number
  width: number
  height: number
  rotation: number
  zIndex: number
  text: string | null
  style: ShapeStyle
  props: ShapeProps
  createdAt: Date
  updatedAt: Date
}

/**
 * A shape-to-shape connector (Phase 1: shapes-and-connectors). Endpoints are
 * dedicated indexed columns (FR-031), never inside a JSON blob. No stored
 * path — geometry is derived at render time from both endpoints' bounds
 * (FR-031a).
 */
export interface Connector {
  id: string
  whiteboardId: string
  sourceShapeId: string
  targetShapeId: string
  style: ConnectorStyle
  createdAt: Date
  updatedAt: Date
}

/**
 * Canvas comment / annotation (GH #110). A root comment (`parentId === null`)
 * anchors a thread either to a table (`targetType === 'table'`,
 * `targetTableId` set) or to a free canvas point (`targetType === 'point'`,
 * `positionX`/`positionY` set). A reply (`parentId` set) always stores
 * `targetType === 'thread'` and null target/position fields — target
 * consistency only applies to the root. `resolved`/`resolvedBy`/`resolvedAt`
 * are meaningful only on the root; replies leave them at their defaults.
 */
export interface Comment {
  id: string
  whiteboardId: string
  parentId: string | null
  targetType: string
  targetTableId: string | null
  positionX: number | null
  positionY: number | null
  authorId: string
  body: string
  resolved: boolean
  resolvedBy: string | null
  resolvedAt: Date | null
  createdAt: Date
  updatedAt: Date
}

/**
 * Comment row joined with its author's display fields (read/broadcast
 * payload shape) — commenters may be offline, so this is resolved from the
 * `User` table directly, never from the live `activeUsers` collaboration set.
 */
export interface CommentWithAuthor extends Comment {
  authorName: string
  authorEmail: string
}

/**
 * A canvas board (FigJam-style canvas engine, milestone 1).
 *
 * A deliberately separate board kind from `Whiteboard`: the canvas engine
 * renders every pixel itself and owns its own elements, so the two share no
 * rows. `folderId` mirrors `Whiteboard` so both kinds can sit side by side
 * in the navigator later.
 */
export interface CanvasBoard {
  id: string
  name: string
  projectId: string
  folderId: string | null
  createdAt: Date
  updatedAt: Date
}

/**
 * A stored canvas element — the ROW, not the engine value.
 *
 * The name is not incidental. `src/lib/canvas-engine/scene.ts` exports a
 * `CanvasElement` too, and the two are deliberately different types:
 *
 *   - this record uses `positionX`/`positionY`, matching every other table
 *     in the schema, and carries `createdAt`/`updatedAt`;
 *   - the engine's element uses `x`/`y` in world space and knows nothing
 *     about storage.
 *
 * `mapCanvasElement` in src/db.ts and `toEngineElement` in
 * src/lib/canvas-element-adapter.ts are the only places the two vocabularies
 * meet. Keeping them apart is the same discipline `camera.ts` enforces for
 * screen-versus-world coordinates, and for the same reason: the two bugs
 * this repo has already paid for (W1, W3) were both a coordinate space used
 * where another was meant.
 */
export interface CanvasElementRecord {
  id: string
  boardId: string
  kind: CanvasElementKind
  positionX: number
  positionY: number
  width: number
  height: number
  rotation: number
  zIndex: number
  text: string | null
  style: CanvasElementStyle
  props: CanvasElementProps
  /** Monotonic write counter — see schema-sql.ts's "revision" column comment. */
  revision: number
  createdAt: Date
  updatedAt: Date
}
