// src/data/models.ts
// Hand-written row types for the raw-SQLite data layer.
//
// These replace the types previously generated by `@prisma/client`. They
// describe the SHAPE the data layer returns to the rest of the app after
// row-mapping (see src/db.ts): datetimes as `Date`, integer booleans as
// `boolean`, and JSONB text columns parsed into values.

import type { Cardinality, ProjectRoleValue } from './schema'

/** Permissive JSON value (mirrors the old Prisma `JsonValue`). */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | Array<JsonValue>

export interface User {
  id: string
  username: string
  email: string
  passwordHash: string
  failedLoginAttempts: number
  lockedUntil: Date | null
  createdAt: Date
  updatedAt: Date
}

export interface Session {
  id: string
  tokenHash: string
  userId: string
  expiresAt: Date
  createdAt: Date
}

export interface ProjectMember {
  id: string
  projectId: string
  userId: string
  role: ProjectRoleValue
  createdAt: Date
  updatedAt: Date
}

export interface Project {
  id: string
  name: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  ownerId: string | null
}

export interface ProjectInvite {
  id: string
  projectId: string
  role: ProjectRoleValue
  tokenHash: string
  createdByUserId: string
  maxUses: number | null
  usedCount: number
  expiresAt: Date
  revokedAt: Date | null
  createdAt: Date
}

export interface WhiteboardShareLink {
  id: string
  whiteboardId: string
  tokenHash: string
  createdByUserId: string
  expiresAt: Date | null
  revokedAt: Date | null
  createdAt: Date
}

/**
 * Full-state capture of a whiteboard's diagram (GH #107 version history), as
 * returned FRESH by `captureWhiteboardState` — nested `createdAt`/`updatedAt`
 * are real `Date` objects straight from the data layer, never round-tripped
 * through JSON. D1: stored as a single self-contained JSON blob so it is
 * immune to future live-schema drift — everything needed to restore lives in
 * this object, including original entity UUIDs (reused verbatim on restore,
 * D3).
 *
 * See `PersistedSnapshotPayload` for the shape this becomes once it has been
 * written to and reloaded from the DB — the two are NOT interchangeable.
 */
export interface SnapshotPayload {
  whiteboard: {
    name: string
    canvasState: JsonValue | null
    textSource: string | null
  }
  tables: Array<DiagramTable & { columns: Array<Column> }>
  relationships: Array<Relationship>
  areas: Array<Area>
}

/**
 * Replaces `createdAt`/`updatedAt` with `string` — mirrors exactly what
 * `JSON.stringify`/`JSON.parse` do to a `Date` field during the
 * `toDbJson`/`fromDbJson` round-trip (`JSON.stringify` serializes a `Date` to
 * an ISO string; `JSON.parse` never revives it back to a `Date`). Keeps the
 * Date-vs-string mismatch statically visible in the type system instead of
 * relying solely on a code comment — a future `Date`-typed field added to
 * DiagramTable/Column/Relationship/Area will fail to compile here until this
 * mapped type (or its usage) is updated, rather than silently reaching
 * `restoreWhiteboardFromSnapshot` as an un-coerced `Date`.
 */
type WithPersistedDates<T extends { createdAt: Date; updatedAt: Date }> = Omit<
  T,
  'createdAt' | 'updatedAt'
> & {
  createdAt: string
  updatedAt: string
}

/**
 * The as-stored-and-reloaded shape of a SnapshotPayload — what
 * `WhiteboardSnapshot.payload` actually is once `mapWhiteboardSnapshot` has
 * parsed it back out of the `payload` JSON column (see `fromDbJson`). Every
 * nested `createdAt`/`updatedAt` is a `string`, matching what
 * `coerceStoredDate` in `whiteboard-snapshot.ts` is defending against at
 * runtime.
 */
export interface PersistedSnapshotPayload {
  whiteboard: {
    name: string
    canvasState: JsonValue | null
    textSource: string | null
  }
  tables: Array<
    WithPersistedDates<DiagramTable> & {
      columns: Array<WithPersistedDates<Column>>
    }
  >
  relationships: Array<WithPersistedDates<Relationship>>
  areas: Array<WithPersistedDates<Area>>
}

/**
 * WhiteboardSnapshot row (GH #107) — an immutable, point-in-time capture of
 * a whiteboard's full diagram state. `isAuto` distinguishes user-initiated
 * saves from the automatic "before restore" safety snapshot (D2). `payload`
 * is always the DB-reloaded (persisted) shape — see `PersistedSnapshotPayload`.
 */
export interface WhiteboardSnapshot {
  id: string
  whiteboardId: string
  label: string | null
  payload: PersistedSnapshotPayload
  createdByUserId: string | null
  isAuto: boolean
  createdAt: Date
}

export interface Folder {
  id: string
  name: string
  projectId: string
  parentFolderId: string | null
  createdAt: Date
  updatedAt: Date
}

export interface Whiteboard {
  id: string
  name: string
  projectId: string
  folderId: string | null
  canvasState: JsonValue | null
  textSource: string | null
  createdAt: Date
  updatedAt: Date
}

export interface DiagramTable {
  id: string
  whiteboardId: string
  name: string
  description: string | null
  positionX: number | null
  positionY: number | null
  width: number | null
  height: number | null
  createdAt: Date
  updatedAt: Date
}

export interface Column {
  id: string
  tableId: string
  name: string
  dataType: string
  isPrimaryKey: boolean
  isForeignKey: boolean
  isUnique: boolean
  isNullable: boolean
  description: string | null
  order: number
  createdAt: Date
  updatedAt: Date
}

export interface Relationship {
  id: string
  whiteboardId: string
  sourceTableId: string
  targetTableId: string
  sourceColumnId: string
  targetColumnId: string
  cardinality: Cardinality
  label: string | null
  routingPoints: JsonValue | null
  createdAt: Date
  updatedAt: Date
}

export interface CollaborationSession {
  id: string
  whiteboardId: string
  userId: string
  socketId: string
  cursor: JsonValue | null
  lastActivityAt: Date
  createdAt: Date
}

/**
 * Subject area (GH #106) — a named, colored background region that groups
 * tables. Membership is explicit (`memberTableIds`); areas do NOT own table
 * positions. `color` stores a palette id (see src/lib/area-colors.ts).
 */
export interface Area {
  id: string
  whiteboardId: string
  name: string
  color: string
  positionX: number
  positionY: number
  width: number
  height: number
  memberTableIds: Array<string>
  createdAt: Date
  updatedAt: Date
}
